export const demoCopy = {
  backToProjects: 'All projects',
  configureCta: 'Configure your unit',
  openConfigurator: 'Configure your unit',
  saveConfiguration: 'Save configuration',
  saveToast: 'Configuration saved — specification summary copied for demo.',
  preview360: '3D tour',
  previewPhoto: 'Photo',
  previewVideo: 'Video',
  previewAria: 'Preview mode',
  designAria: 'Design palette',
  summaryTitle: 'Summary',
  configurationTitle: 'Your configuration',
  descriptionTitle: 'Description',
  chooseDesignTitle: 'Choose design',
  headerSampleLabel: 'Configurator sample',
  galleryAria: 'Project gallery',
  galleryPrev: 'Previous image',
  galleryNext: 'Next image',
  hotspotPanelHint:
    'Expand a zone below or tap a spot on the photo to pick materials.',
  hotspotPopupPrereq:
    'Select olive green cabinets, or blue shelves for tile options.',
  hotspotPopupComingSoon: 'Configuration options for this design are coming soon.',
  hotspotDebugHint:
    'Pick a view below, drag the yellow points on the photo, then Save. Repeat for main photo, kitchen, wall, and work zone.',
  editingZoneLabel: 'Editing',
  selectionSummaryTitle: 'Your selection',
  packageBaseLabel: 'Design package',
  upgradesLabel: 'Material upgrades',
  totalLabel: 'Total',
  includedLabel: 'Included',
  packageDefaultsIncluded: 'Package defaults included',
  downloadConfiguration: 'Download specification',
  downloadToast: 'Specification file downloaded.',
  kuulaLoading: '360 tour loading…',
  kuulaPending: '360 tour — assets pending',
} as const
