export const projectsCopy = {
  pageTitle: 'New developments',
  pageSubtitle: 'Residential projects with photorealistic visualization, interactive tours, and online unit configuration.',
  searchPlaceholder: 'Search name, district, metro',
  filterCity: 'City',
  filterType: 'Property type',
  filterStatus: 'Status',
  allCities: 'All cities',
  allTypes: 'All types',
  allStatuses: 'All statuses',
  viewAria: 'Projects view',
  noResults: 'No projects match your filters.',
  backToProjects: 'All projects',
  configureUnit: 'Configure your unit',
  viewProject: 'View project',
  fromPrice: 'from',
  walkToMetro: 'min walk',
  amenitiesLabel: 'Project highlights',
  onSale: 'On sale',
  comingSoon: 'Coming soon',
  lastUnits: 'Last units',
  residentialComplex: 'Residential complex',
  townhouses: 'Townhouses',
  villas: 'Villas',
  apartments: 'Apartments',
  mixedUse: 'Mixed-use',
} as const
