import type { ResidentialProject } from './types'

const B = 'https://adiptvvvorqtpxpcylcn.supabase.co/storage/v1/object/public/workspace-studio/00000000-0000-4000-8000-000000000001/media'

/** Offline / build-time fallback when Postgres pooler is unavailable. */
export const STATIC_RESIDENTIAL_PROJECTS: ResidentialProject[] = [
  {
    id: 'w3010001-0027-4000-8000-000000000001',
    slug: 'urban-oasis',
    title: 'Urban Oasis',
    subtitle: 'Urban Oasis',
    description:
      'Mixed-use office and residential complex with fully designed studio interiors. Configure design package, kitchen, wall colour, and furniture with a live 360 tour.',
    city: 'Berlin',
    district: 'Mitte',
    locationLabel: 'Berlin · Mitte',
    priceFrom: 395_000,
    priceCurrency: 'EUR',
    priceLabel: 'from €395k',
    metroStation: 'Naturkundemuseum',
    walkMinutes: 7,
    status: 'on_sale',
    statusLabel: 'On sale',
    propertyType: 'mixed_use',
    propertyTypeLabel: 'Mixed use',
    heroImage: '/demo/configurator/urban-oasis/design-1/08.jpg',
    galleryImages: [
      '/demo/configurator/urban-oasis/design-1/08.jpg',
      '/demo/configurator/urban-oasis/design-2/08.jpg',
      '/demo/configurator/urban-oasis/design-3/08.jpg',
    ],
    featureTags: [
      { id: 'studio', label: 'Studio layouts', variant: 'primary' },
      { id: 'configurator', label: 'Interior configurator', variant: 'default' },
      { id: 'tour', label: '360 tour', variant: 'default' },
    ],
    amenityTags: ['3 design packages', 'Kitchen customisation', 'Kuula 360 walkthrough'],
    hasConfigurator: true,
    featured: true,
    workCategory: 'Complex',
  },
  {
    id: 'w3010001-0023-4000-8000-000000000001',
    slug: 'residence-tower',
    title: 'Residence Tower',
    subtitle: 'Complete Marketing Package',
    description:
      'A new residential complex with 24 individually designed apartments. Explore exteriors, floor plans, cinematic film, and sales gallery materials.',
    city: 'Berlin',
    district: 'Friedrichshain',
    locationLabel: 'Berlin · Friedrichshain',
    priceFrom: 420_000,
    priceCurrency: 'EUR',
    priceLabel: 'from €420k',
    metroStation: 'Warschauer Straße',
    walkMinutes: 8,
    status: 'on_sale',
    statusLabel: 'On sale',
    propertyType: 'residential_complex',
    propertyTypeLabel: 'Residential complex',
    heroImage: `${B}/a179e98a-0891-43f4-ac30-c4d4a6b9e2c6.webp`,
    galleryImages: [
      `${B}/a179e98a-0891-43f4-ac30-c4d4a6b9e2c6.webp`,
      `${B}/d3a5a064-60a2-4fe1-a0e0-8e9e566f43bf.webp`,
    ],
    featureTags: [
      { id: 'series', label: 'Next Series', variant: 'primary' },
      { id: 'start', label: 'Sales launch', variant: 'default' },
      { id: 'river', label: 'River views', variant: 'default' },
    ],
    amenityTags: ['24 unique interior layouts', 'Interactive 3D tours'],
    hasConfigurator: false,
    featured: true,
    workCategory: 'Complex',
  },
  {
    id: 'w3010001-0024-4000-8000-000000000001',
    slug: 'quartier-a15-residential',
    title: 'Quartier A15 Residential',
    subtitle: 'Modern Classic in Berlin',
    description:
      'Holistic visual presentation for a residential project in Berlin — architectural context to immersive interior experience.',
    city: 'Berlin',
    district: 'Charlottenburg',
    locationLabel: 'Berlin · Charlottenburg',
    priceFrom: 385_000,
    priceCurrency: 'EUR',
    priceLabel: 'from €385k',
    metroStation: 'Richard-Wagner-Platz',
    walkMinutes: 12,
    status: 'on_sale',
    statusLabel: 'On sale',
    propertyType: 'residential_complex',
    propertyTypeLabel: 'Residential complex',
    heroImage: `${B}/3746ecdf-1866-4294-9b63-704a933bd6aa.webp`,
    galleryImages: [
      `${B}/3746ecdf-1866-4294-9b63-704a933bd6aa.webp`,
      `${B}/05e3038b-ef1f-4cee-8ddd-362adab82932.webp`,
    ],
    featureTags: [
      { id: 'classic', label: 'Modern Classic', variant: 'primary' },
      { id: 'interiors', label: 'Fully designed interiors', variant: 'default' },
    ],
    amenityTags: ['Exterior renders', 'Interior package', '3D tour'],
    hasConfigurator: false,
    featured: true,
    workCategory: 'Complex',
  },
  {
    id: 'w3010001-0018-4000-8000-000000000001',
    slug: 'waterfront-redevelopment-residential-complex',
    title: 'Waterfront Redevelopment & Residential Complex',
    subtitle: 'Urban Renewal',
    description:
      'Large-scale waterfront redevelopment — new residential complex and public promenade revitalizing the district.',
    city: 'Hamburg',
    district: 'HafenCity',
    locationLabel: 'Hamburg · HafenCity',
    priceFrom: 510_000,
    priceCurrency: 'EUR',
    priceLabel: 'from €510k',
    metroStation: 'Überseequartier',
    walkMinutes: 6,
    status: 'coming_soon',
    statusLabel: 'Coming soon',
    propertyType: 'residential_complex',
    propertyTypeLabel: 'Residential complex',
    heroImage: `${B}/63534f15-51f2-40b5-a211-af2af0fe74b5.webp`,
    galleryImages: [
      `${B}/63534f15-51f2-40b5-a211-af2af0fe74b5.webp`,
      `${B}/3d54d97d-3a78-4e4a-985b-ad71b5820e70.webp`,
    ],
    featureTags: [
      { id: 'waterfront', label: 'Waterfront', variant: 'primary' },
      { id: 'promenade', label: 'Public promenade', variant: 'default' },
    ],
    amenityTags: ['Masterplan', 'Aerial views', 'District renewal'],
    hasConfigurator: false,
    featured: true,
    workCategory: 'Exterior',
  },
  {
    id: 'w3010001-0021-4000-8000-000000000001',
    slug: 'dubai-townhouses-residential-community',
    title: 'Dubai Townhouses Residential Community',
    subtitle: 'Modern Desert Living',
    description: 'Premium townhouse community in Dubai — modern forms, landscaping, and vibrant lifestyle.',
    city: 'Dubai',
    district: 'Arabian Ranches',
    locationLabel: 'Dubai · Arabian Ranches',
    priceFrom: 1_850_000,
    priceCurrency: 'AED',
    priceLabel: 'from 1.85M AED',
    status: 'on_sale',
    statusLabel: 'On sale',
    propertyType: 'townhouses',
    propertyTypeLabel: 'Townhouses',
    heroImage: `${B}/8ed3732a-3a64-4a5a-b941-57d3a7b0948c.webp`,
    galleryImages: [
      `${B}/8ed3732a-3a64-4a5a-b941-57d3a7b0948c.webp`,
      `${B}/90d3c82f-b275-4ce3-96cd-6671a5974f26.webp`,
    ],
    featureTags: [
      { id: 'premium', label: 'Premium community', variant: 'primary' },
      { id: 'landscape', label: 'Lush landscaping', variant: 'default' },
    ],
    amenityTags: ['Townhouse typologies', 'Pool & garden', 'Exterior package'],
    hasConfigurator: false,
    featured: false,
    workCategory: 'Exterior',
  },
  {
    id: 'w3010001-0028-4000-8000-000000000001',
    slug: 'richter-garten',
    title: 'Richter-Gärten',
    subtitle: 'Townhouse Community',
    description: 'Comprehensive visual solution for a new townhouse complex with 3D tours and cinematic animation.',
    city: 'Munich',
    district: 'Trudering',
    locationLabel: 'Munich · Trudering',
    priceFrom: 890_000,
    priceCurrency: 'EUR',
    priceLabel: 'from €890k',
    metroStation: 'Trudering',
    walkMinutes: 14,
    status: 'on_sale',
    statusLabel: 'On sale',
    propertyType: 'townhouses',
    propertyTypeLabel: 'Townhouses',
    heroImage: `${B}/22e436aa-09a1-4abf-a924-a769e4315a65.webp`,
    galleryImages: [
      `${B}/22e436aa-09a1-4abf-a924-a769e4315a65.webp`,
      `${B}/49a6a4bd-196e-47e1-8409-7a32975f6491.webp`,
    ],
    featureTags: [
      { id: 'townhouses', label: 'Townhouse community', variant: 'primary' },
      { id: 'tour', label: '3D tour', variant: 'default' },
    ],
    amenityTags: ['Facade adaptation', 'Cinematic animation', 'Private gardens'],
    hasConfigurator: false,
    featured: false,
    workCategory: 'Complex',
  },
  {
    id: 'w3010001-0004-4000-8000-000000000001',
    slug: 'skyline-penthouse',
    title: 'Skyline Penthouse',
    subtitle: 'Luxury Above the Clouds',
    description: 'Show apartment penthouse with luxury finishes and panoramic city views.',
    city: 'Berlin',
    district: 'Mitte',
    locationLabel: 'Berlin · Mitte',
    priceFrom: 1_150_000,
    priceCurrency: 'EUR',
    priceLabel: 'from €1.15M',
    metroStation: 'Hausvogteiplatz',
    walkMinutes: 5,
    status: 'last_units',
    statusLabel: 'Last units',
    propertyType: 'apartments',
    propertyTypeLabel: 'Apartments',
    heroImage: `${B}/31401b66-3649-4f0e-b5d9-86673ab66163.webp`,
    galleryImages: [
      `${B}/31401b66-3649-4f0e-b5d9-86673ab66163.webp`,
      `${B}/d089f55b-b330-47c2-823b-edcf8a3744ed.webp`,
    ],
    featureTags: [
      { id: 'penthouse', label: 'Penthouse', variant: 'primary' },
      { id: 'skyline', label: 'Skyline views', variant: 'default' },
    ],
    amenityTags: ['Show apartment', 'Luxury finishes', 'City views'],
    hasConfigurator: false,
    featured: false,
    workCategory: 'Interior',
  },
]
